spring:
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.xiayu.provicer.domain
  mapper-locations: classpath:mapper/*.xml


server:
  port: 9001


# jasypt 加密的根（盐）
jasypt:
  encryptor:
    password: xiayu
