spring:
  profiles:
    active: test

server:
  port: 9000

mybatis:
  # 实体类的存放路径
  type-aliases-package: com.xiayu.oauth.domain
  mapper-locations: classpath:mapper/*.xml

# jasypt 加密的根（盐）
jasypt:
  encryptor:
    password: xiayu

